### PR TITLE
modify check for existing files that properly splits name and extension

### LINKED ISSUE #1092: [wizard] source archive files with same name returns unknown archive format error
I ran into this issue when trying to build something requiring multiple source archives, but they end up having identical names.

Steps to reproduce behavior:
```
using BinaryBuilder; step = BinaryBuilder.run_wizard()
...


Welcome to the BinaryBuilder wizard.  We'll get you set up in no time.

			# Step 1: Select your platforms

Make a platform selection
   All Supported Platforms
   Select by Operating System
 > Fully Custom Platform Choice

Select platforms
[press: d=done, a=all, n=none]
   [ ] Platform("i686", "linux"; libc = "glibc")
 > [X] Platform("x86_64", "linux"; libc = "glibc")
   [ ] Platform("aarch64", "linux"; libc = "glibc")
   [ ] Platform("armv7l", "linux"; call_abi = "eabihf", libc = "glibc")
   [ ] Platform("powerpc64le", "linux"; libc = "glibc")
   [ ] Platform("i686", "linux"; libc = "musl")
   [ ] Platform("x86_64", "linux"; libc = "musl")
   [ ] Platform("aarch64", "linux"; libc = "musl")
   [ ] Platform("armv7l", "linux"; call_abi = "eabihf", libc = "musl")
v  [ ] Platform("x86_64", "macos"; )

			# Step 2a: Obtain the source code

Please enter a URL (git repository or compressed archive) containing the source code to build:
> https://github.com/dlang/dmd/archive/refs/tags/v2.097.2.tar.gz


Would you like to download additional sources?  [y/N]: y
Please enter a URL (git repository or compressed archive) containing the source code to build:
> https://github.com/dlang/phobos/archive/refs/tags/v2.097.2.tar.gz


Would you like to download additional sources?  [y/N]: n

			# Step 2b: Obtain binary dependencies (if any)

Do you require any (binary) dependencies?  [y/N]: n

Enter a name for this project.  This will be used for filenames:
> dmd

Enter a version number for this project:
> 2.97.2

Do you want to customize the set of compilers? [y/N]: n
			# Step 3: Build for Linux x86_64 {libc=glibc}

You will now be dropped into the cross-compilation environment.
Please compile the package. Your initial compilation target is x86_64-linux-gnu
The $prefix environment variable contains the target directory.
Once you are done, exit by typing `exit` or `^D`

Unknown archive format
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] (::BinaryBuilderBase.var"#66#68"{String, BinaryBuilderBase.SetupSource{ArchiveSource}, Bool})()
    @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/bwZqa/src/Prefix.jl:300
  [3] cd(f::BinaryBuilderBase.var"#66#68"{String, BinaryBuilderBase.SetupSource{ArchiveSource}, Bool}, dir::String)
    @ Base.Filesystem ./file.jl:106
  [4] #setup#65
    @ ~/.julia/packages/BinaryBuilderBase/bwZqa/src/Prefix.jl:288 [inlined]
  [5] setup(source::BinaryBuilderBase.SetupSource{ArchiveSource}, targetdir::String, verbose::Bool)
    @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/bwZqa/src/Prefix.jl:284
  [6] setup_workspace(build_path::String, sources::Vector{Any}, target_platform::Platform, host_platform::Platform; verbose::Bool)
    @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/bwZqa/src/Prefix.jl:376
  [7] step34(state::BinaryBuilder.Wizard.WizardState)
    @ BinaryBuilder.Wizard ~/.julia/packages/BinaryBuilder/n6Mft/src/wizard/interactive_build.jl:519
  [8] run_wizard(state::Nothing)
    @ BinaryBuilder.Wizard ~/.julia/packages/BinaryBuilder/n6Mft/src/Wizard.jl:104
  [9] run_wizard()
    @ BinaryBuilder.Wizard ~/.julia/packages/BinaryBuilder/n6Mft/src/Wizard.jl:87
 [10] top-level scope
    @ REPL[13]:1
 [11] eval
    @ ./boot.jl:360 [inlined]
 [12] eval_user_input(ast::Any, backend::REPL.REPLBackend)
    @ REPL /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:139
 [13] repl_backend_loop(backend::REPL.REPLBackend)
    @ REPL /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:200
 [14] start_repl_backend(backend::REPL.REPLBackend, consumer::Any)
    @ REPL /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:185
 [15] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool)
    @ REPL /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:317
 [16] run_repl(repl::REPL.AbstractREPL, consumer::Any)
    @ REPL /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:305
 [17] (::Base.var"#874#876"{Bool, Bool, Bool})(REPL::Module)
    @ Base ./client.jl:387
 [18] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
 [19] invokelatest
    @ ./essentials.jl:706 [inlined]
 [20] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
    @ Base ./client.jl:372
 [21] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:302
 [22] _start()
    @ Base ./client.jl:485

WizardState [step3]

julia> 

```
Not sure if this is something on the BB side or something in the alpine image you get dropped into?
I did notice [BB appending numbers to filenames](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/6467218420c8f709a1324b42a7c22fcb22e3b0fb/src/wizard/obtain_source.jl#L163-L170)
```
julia> step.source_files
2-element Vector{BinaryBuilderBase.SetupSource}:
 BinaryBuilderBase.SetupSource{ArchiveSource}("/tmp/jl_I4gCdg/v2.097.2.tar.gz", "10e8fc9b99864bf68f384ca85f0c527221478be08d331ac477a90a2d83b71f4f", "", false)
 BinaryBuilderBase.SetupSource{ArchiveSource}("/tmp/jl_I4gCdg/v2.097.2.tar_1.gz", "3f407f94d5d50a43498acf7f463f56a96f66534901068f8d6be850a1bd12135c", "", false)

```
but I can decompress them with no issues on my local machine?
```
/tmp/jl_IUYriu$ tar -xvf v2.097.1.tar_1.gz 
phobos-2.097.1/
phobos-2.097.1/.circleci/
phobos-2.097.1/.circleci/config.yml
phobos-2.097.1/.circleci/run.sh
...
```
Unsure what else to look at from here

Julia versioninfo

```
julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, broadwell)

```

### PR DESCRIPTION
**Pull request by Crghilardi**
This PR modifies the step in the wizard that modifies file names if duplicated file names exist when downloading sources.

If the files have multiple extensions like `blahh.tar.gz`, `splitext` doesn't split enough and you end up with `foobar.tar_n.gz` which doesn't match [the list of extensions we check against](https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/eb8ade82382394ca54a05dc9e7bb27cf2e5ba050/src/Sources.jl#L38-L39). With this, you should now end up with `foobar_n.tar.gz`

closes #1092

### CODE REVIEW

File: src/wizard/obtain_source.jl [hunk 1]
```diff
@@ -161,7 +161,13 @@ function download_source(state::WizardState)
...
 
         if isfile(source_path)
-            name, ext = splitext(basename(source_path))
+            if occursin(".tar.", basename(source_path))
+                #match everything up to but not including ".tar.*" to strip multiple file extensions
+                m = match(r"^.*(?=(\.tar\.([\s\S]*)))", basename(source_path))
+                name, ext = m.match, m.captures[1]
+            else
+                name, ext = splitext(basename(source_path))
+            end
```
Comment (giordano) [inline src/wizard/obtain_source.jl:170]: I'd do something like
```suggestion
            # Try to match everything up to but not including ".tar.*" to strip multiple file extensions
            m = match(r"^.+(?=(\.tar\.([\s\S]+)))", basename(source_path))
            name, ext = if isnothing(m)
                splitext(basename(source_path))
            else
                m.match, m.captures[1]
            end
```
The idea is that you do the match once, if it's successful you use its result, otherwise go with plain `splitext`.  What do you think?

**Comment by giordano** [comment]
Ok, now big question: would you be able to add a test about this?  We're already using `*.tar.gz` sources, it shouldn't be too much difficult, hopefully.

**Comment by Crghilardi** [comment]
I took a shot at adding a test, luckily we actually have a "download two files with the same name" scenario already coded up.
 My first attempt was to just pass them through `BinaryBuilderBase.setup.(state.source_files, "./", false)` but I couldn't make that work with `@test` for some reason so I moved to checking the extensions against the `tar_extension` array. That is essentially all I'm trying to patch in this PR anyway
