### PR TITLE
fix JSON.lower(d::Dependency) for 1.4

### LINKED ISSUE #723: `show_json(::Dependency)` broke on Julia 1.4
```
ERROR: LoadError: type VersionNumber has no field ranges
Stacktrace:
 [1] getproperty at ./Base.jl:33 [inlined]
 [2] lower(::Dependency) at /depot/packages/BinaryBuilder/LuheW/src/Dependencies.jl:94
 [3] show_json(::JSON.Writer.CompactContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::Dependency) at /depot/packages/JSON/d89fA/src/Writer.jl:314
 [4] show_element(::JSON.Writer.CompactContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::Dependency) at /depot/packages/JSON/d89fA/src/Writer.jl:218
 [5] show_json(::JSON.Writer.CompactContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::Array{BinaryBuilder.AbstractDependency,1}) at /depot/packages/JSON/d89fA/src/Writer.jl:293
 [6] show_pair(::JSON.Writer.CompactContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::String, ::Array{BinaryBuilder.AbstractDependency,1}) at /depot/packages/JSON/d89fA/src/Writer.jl:241
 [7] show_pair(::JSON.Writer.CompactContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::Pair{String,Any}) at /depot/packages/JSON/d89fA/src/Writer.jl:243
 [8] show_json(::JSON.Writer.CompactContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::Dict{String,Any}) at /depot/packages/JSON/d89fA/src/Writer.jl:271
 [9] #show_json#3 at /depot/packages/JSON/d89fA/src/Writer.jl:325 [inlined]
 [10] show_json at /depot/packages/JSON/d89fA/src/Writer.jl:324 [inlined]
 [11] print(::Base.GenericIOBuffer{Array{UInt8,1}}, ::Dict{String,Any}) at /depot/packages/JSON/d89fA/src/Writer.jl:349
 [12] sprint(::Function, ::Dict{String,Any}; context::Nothing, sizehint::Int64) at ./strings/io.jl:105
 [13] sprint at ./strings/io.jl:101 [inlined]
 [14] json(::Dict{String,Any}) at /depot/packages/JSON/d89fA/src/Writer.jl:365
 [15] autobuild(::AbstractString, ::AbstractString, ::VersionNumber, ::Array{#s1079,1} where #s1079<:BinaryBuilder.AbstractSource, ::AbstractString, ::Array{T,1} where T, ::Array{#s1078,1} where #s1078<:Product, ::Array{#s1077,1} where #s1077<:BinaryBuilder.AbstractDependency; verbose::Bool, debug::Bool, skip_audit::Bool, ignore_audit_errors::Bool, autofix::Bool, code_dir::Union{Nothing, String}, require_license::Bool, lazy_artifacts::Bool, meta_json_stream::Any, kwargs::Any) at /depot/packages/BinaryBuilder/LuheW/src/AutoBuild.jl:524
 [16] build_tarballs(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any; kwargs::Any) at /depot/packages/BinaryBuilder/LuheW/src/AutoBuild.jl:183
 [17] top-level scope at /agent/_work/1/s/L/LLVM/LLVM@9.0.1/build_tarballs.jl:5
 [18] include(::Module, ::String) at ./Base.jl:377
 [19] exec_options(::Base.JLOptions) at ./client.jl:288
 [20] _start() at ./client.jl:484
in expression starting at /agent/_work/1/s/L/LLVM/LLVM@9.0.1/build_tarballs.jl:5

```

From: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=2447&view=logs&j=96c13d9d-dfd2-51e5-2f76-4a0b3ce09abc&t=09532434-8b0a-5f0e-118d-a3181cde5ec8

https://github.com/JuliaPackaging/Yggdrasil/pull/687

### PR DESCRIPTION
**Pull request by vchuravy**
Fixes #723

### CODE REVIEW

**Comment by vchuravy** [comment]
needed for https://github.com/JuliaPackaging/Yggdrasil/pull/710

File: src/Dependencies.jl [hunk 1]
```diff
@@ -91,14 +91,25 @@ end
...
+
+major(v::VersionNumber) = v.major
+minor(v::VersionNumber) = v.minor
+patch(v::VersionNumber) = v.patch
+major(v::Pkg.Types.VersionBound) = v.t[1]
+minor(v::Pkg.Types.VersionBound) = v.t[2]
+patch(v::Pkg.Types.VersionBound) = v.t[3]
+__version(v::VersionNumber) = v
+__version(v::Pkg.Types.VersionSpec) = v.ranges[1].lower
+version(d::Union{Dependency, BuildDependency}) = __version(d.pkg.version)
```
Comment (giordano) [inline src/Dependencies.jl:103]: Minor nitpick:
```suggestion
version(d::AbstractDependency) = __version(getpkg(d).version)
```

So what happened is that in Julia v1.4 `d.pkg.version` is `VersionNumber` instead of `Pkg.Types.VersionBound` and this changed between v1.4-rc1 and v1.4?

Maybe add a test in [`test/declarative.jl`](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/master/test/declarative.jl)?

**Comment by vchuravy** [comment]
> So what happened is that in Julia v1.4 d.pkg.version is VersionNumber instead of Pkg.Types.VersionBound and this changed between v1.4-rc1 and v1.4?

It is allowed to be both... 

> Maybe add a test in test/declarative.jl?

Sure, bit busy right now with fixing other things.
